### ISSUE TITLE
Merging timing

### ISSUE THREAD

**Issue by kubenstein** [mp40/PCCS-Helper#49]
Hello,
I was not able to follow latest changes unfortunately but Im glad the project is actively developed! Keep it up!
I want to suggest you a nice trick: How about having a policy to never merge PR the same day you coded it? ^^
I myself follow this policy because of two things. First, when Im the only dev on a project, the only way to meaningful review my own code is to give myself time to forget the details. The way to do it is just to have a break from a particular piece of code.
And second: such a policy will introduce a process and a "rhythm". Things become more organized. It teaches us to think about changes as dependencies, revealing internal code relationships, aka avoiding merge conlicts.
Hot fixes can be exceptions but the truth is, often nothing actually bad will happen if we wait a day or two.
wdyt?

cheers!

**Comment by mp40** [comment]
Hi Kuba,
Thanks for the advice.
I'll work on resisting the urge to merge and move on.
The instant gratification of seeing contributions go green is nice, but as you pointed out is not healthy for the long term.

**Comment by kubenstein** [comment]
do you mean contribution mosaic? we can work on other task meanwhile ^^ ofc on hobby projects nothing really matters that much (thats why i try to make everything matter a lot! ^^)
